// Resolver.c — one-shot kernel physical address resolver.
//
// DriverEntry resolves a fixed symbol list via MmGetPhysicalAddress,
// writes results to \??\F:\vsprojs\dayzdriv\logs\sentinel_gpas.txt,
// then returns a non-success status so the SCM unloads it immediately.
//
// Output format (matches hv_client.py _load_sentinel_gpas):
//   Label  0xGPA
//
// Build: see resolver\build.bat

#include <ntddk.h>
#include <ntstrsafe.h>

// ---------------------------------------------------------------------------
// Symbol table — add or remove entries here.
// MmGetSystemRoutineAddress resolves exported ntoskrnl symbols by name.
// ---------------------------------------------------------------------------

typedef struct {
    const WCHAR *Name;
    const char  *Label;
} SYMBOL_ENTRY;

static const SYMBOL_ENTRY g_Symbols[] = {
    { L"KiSystemCall64",          "KiSystemCall64"          },
    { L"NtCreateFile",            "NtCreateFile"            },
    { L"PsInitialSystemProcess",  "PsInitialSystemProcess"  },
    { L"MmSystemRangeStart",      "MmSystemRangeStart"      },
    { L"ExAllocatePoolWithTag",   "ExAllocatePoolWithTag"   },
};
#define SYMBOL_COUNT (sizeof(g_Symbols) / sizeof(g_Symbols[0]))

// ---------------------------------------------------------------------------
// Output path
// ---------------------------------------------------------------------------

#define OUTPUT_PATH L"\\??\\F:\\vsprojs\\dayzdriv\\logs\\sentinel_gpas.txt"

// ---------------------------------------------------------------------------
// Write helpers
// ---------------------------------------------------------------------------

static NTSTATUS WriteAllBytes(HANDLE hFile, const char *buf, ULONG len)
{
    IO_STATUS_BLOCK iosb = {0};
    return ZwWriteFile(hFile, NULL, NULL, NULL, &iosb,
                       (PVOID)buf, len, NULL, NULL);
}

static NTSTATUS WriteStr(HANDLE hFile, const char *s)
{
    ULONG len = 0;
    while (s[len]) len++;
    return WriteAllBytes(hFile, s, len);
}

// ---------------------------------------------------------------------------
// DriverEntry
// ---------------------------------------------------------------------------

NTSTATUS DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath)
{
    UNREFERENCED_PARAMETER(DriverObject);
    UNREFERENCED_PARAMETER(RegistryPath);

    // No unload needed — we self-terminate by returning failure.
    DriverObject->DriverUnload = NULL;

    // Open (create/overwrite) the output file.
    UNICODE_STRING    uPath;
    OBJECT_ATTRIBUTES oa;
    IO_STATUS_BLOCK   iosb = {0};
    HANDLE            hFile = NULL;

    RtlInitUnicodeString(&uPath, OUTPUT_PATH);
    InitializeObjectAttributes(&oa, &uPath, OBJ_CASE_INSENSITIVE | OBJ_KERNEL_HANDLE,
                               NULL, NULL);

    NTSTATUS status = ZwCreateFile(
        &hFile,
        GENERIC_WRITE | SYNCHRONIZE,
        &oa, &iosb,
        NULL,                       // AllocationSize
        FILE_ATTRIBUTE_NORMAL,
        0,                          // no sharing
        FILE_OVERWRITE_IF,
        FILE_SYNCHRONOUS_IO_NONALERT | FILE_NON_DIRECTORY_FILE,
        NULL, 0);

    if (!NT_SUCCESS(status)) {
        DbgPrint("Resolver: ZwCreateFile failed 0x%X\n", status);
        return STATUS_SUCCESS;      // unload cleanly even on file error
    }

    // Write header comment.
    WriteStr(hFile, "# sentinel_gpas.txt — generated by Resolver.sys\r\n");
    WriteStr(hFile, "# Format: Label  0xGPA\r\n");
    WriteStr(hFile, "#\r\n");

    // Resolve each symbol and write a line.
    for (ULONG i = 0; i < SYMBOL_COUNT; i++) {
        UNICODE_STRING uSym;
        RtlInitUnicodeString(&uSym, g_Symbols[i].Name);

        PVOID va = MmGetSystemRoutineAddress(&uSym);
        if (!va) {
            // Symbol not exported — write a commented-out placeholder.
            char line[128];
            RtlStringCbPrintfA(line, sizeof(line),
                               "# UNRESOLVED  %s\r\n", g_Symbols[i].Label);
            WriteStr(hFile, line);
            DbgPrint("Resolver: UNRESOLVED  %s\n", g_Symbols[i].Label);
            continue;
        }

        PHYSICAL_ADDRESS pa = MmGetPhysicalAddress(va);
        if (pa.QuadPart == 0) {
            char line[128];
            RtlStringCbPrintfA(line, sizeof(line),
                               "# NO_PHYS  %s  VA=0x%p\r\n",
                               g_Symbols[i].Label, va);
            WriteStr(hFile, line);
            DbgPrint("Resolver: NO_PHYS  %s  VA=%p\n", g_Symbols[i].Label, va);
            continue;
        }

        // Align GPA down to 4KB page boundary (hv_client validates alignment).
        ULONG64 gpa = (ULONG64)pa.QuadPart & ~0xFFFULL;

        char line[128];
        RtlStringCbPrintfA(line, sizeof(line),
                           "%-32s  0x%012llX\r\n",
                           g_Symbols[i].Label, gpa);
        WriteStr(hFile, line);
        DbgPrint("Resolver: %-32s  VA=%p  GPA=0x%012llX\n",
                 g_Symbols[i].Label, va, gpa);
    }

    ZwClose(hFile);
    DbgPrint("Resolver: wrote %s\n", OUTPUT_PATH);

    // Return STATUS_SUCCESS so SCM sees a clean exit, but the driver has no
    // device object — it will be unloaded after DriverEntry returns.
    return STATUS_SUCCESS;
}
